
version: '3.7'
services:

  go-timesheets-api:
    build: ./backend
    container_name: go-timesheets-api
    networks:
    - core
    - postgres
    env_file:
    - .env

  go-timesheets-frontend:
    build: ./frontend
    container_name: go-timesheets-frontend
    networks:
    - core

networks:
  core:
    name: core
  postgres:
    name: postgres